# Render Deployment Configuration
# This file helps Render understand how to deploy your services

# Backend Service Configuration
services:
  - type: web
    name: multi-department-backend
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: ALLOWED_ORIGINS
        sync: false

# Frontend Service Configuration (if deploying separately)
  - type: web
    name: multi-department-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_API_URL
        sync: false
      - key: REACT_APP_ENV
        value: production
